services:
  - type: web
    name: phishsleuth-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.inference.server:app --host 0.0.0.0 --port 8000"
